Fix missing dependency
chokidar was missing for Electron.

```bash
Error: Cannot find module 'chokidar'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (~/marp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/marp/js/main.js:85:16)
    at Object.<anonymous> (~/marp/js/main.js:114:4)
    at Object.<anonymous> (~/marp/js/main.js:118:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
```