Typo (done) was missing
See this error message:
```
[09:54:33] 'package' errored after 2.85 ms
[09:54:33] ReferenceError in plugin "run-sequence(build)"
Message:
    done is not defined
Stack:
ReferenceError: done is not defined
    at Gulp.<anonymous> (/home/lilian/.local/Marp_presentation_mode/marp/gulpfile.coffee:159:8)
```